// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineForm.Services;

#nullable disable

namespace OnlineFormApi.Migrations
{
    [DbContext(typeof(FormDbContext))]
    [Migration("20230830195359_Migration-InitialMigration")]
    partial class MigrationInitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnlineForm.Data.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Citizenship")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GdprApproved")
                        .HasColumnType("bit");

                    b.Property<string>("IdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<int>("Sex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("OnlineFormApi.Data.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CreatedOn = new DateTime(2023, 8, 30, 21, 53, 59, 835, DateTimeKind.Local).AddTicks(4515),
                            RoleName = "System Administrator 1"
                        },
                        new
                        {
                            Id = -2,
                            CreatedOn = new DateTime(2023, 8, 30, 21, 53, 59, 835, DateTimeKind.Local).AddTicks(4588),
                            RoleName = "Role Administrator"
                        },
                        new
                        {
                            Id = -3,
                            CreatedOn = new DateTime(2023, 8, 30, 21, 53, 59, 835, DateTimeKind.Local).AddTicks(4601),
                            RoleName = "Active Directory Administrator"
                        },
                        new
                        {
                            Id = -4,
                            CreatedOn = new DateTime(2023, 8, 30, 21, 53, 59, 835, DateTimeKind.Local).AddTicks(4611),
                            RoleName = "Page Administrator"
                        },
                        new
                        {
                            Id = -5,
                            CreatedOn = new DateTime(2023, 8, 30, 21, 53, 59, 835, DateTimeKind.Local).AddTicks(4621),
                            RoleName = "System Auditor"
                        },
                        new
                        {
                            Id = -6,
                            CreatedOn = new DateTime(2023, 8, 30, 21, 53, 59, 835, DateTimeKind.Local).AddTicks(4633),
                            RoleName = "Global Auditor"
                        });
                });

            modelBuilder.Entity("PersonRole", b =>
                {
                    b.Property<int>("PersonsId")
                        .HasColumnType("int");

                    b.Property<int>("RolesId")
                        .HasColumnType("int");

                    b.HasKey("PersonsId", "RolesId");

                    b.HasIndex("RolesId");

                    b.ToTable("PersonRole");
                });

            modelBuilder.Entity("PersonRole", b =>
                {
                    b.HasOne("OnlineForm.Data.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineFormApi.Data.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
